import numpy as np
v = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9])
print(v)
print(type(v))
print(v[0])
print(v[-1])
print(v[1:3])
print(np.sort(v))
print(np.sum(v))
b = np.zeros((3, 4))
print(b)
print(type(b))
print(v.ndim)
print(v.shape)
y = np.array(['barber', 'ava', 'chen'])
print(y)
print(np.sort(y))