import numpy as np
from scipy.spatial import distance
pointA=np.array([2,4,6])
pointB=np.array([3,1,7])
ed=distance.euclidean(pointA,pointB)
print("Euclidean distance : ",ed)
se=1/(1+ed)
print("Euclidean similarity : ",se)
md=distance.cityblock(pointA,pointB)
print("Manhattan distance : ",md)
sm=1/(1+md)
print("Euclidean similarity : ",sm)
md3=distance.minkowski(pointA,pointB,p=1)
print("Minkowski distance at p = 1: ",md3)
s=1/(1+md3)
print("minkowski similarity : ",s)
md3=distance.minkowski(pointA,pointB,p=2)
print("Minkowski distance at p = 2: ",md3)
s=1/(1+md3)
print("minkowski similarity : ",s)
md3=distance.minkowski(pointA,pointB,p=3)
print("Minkowski distance at p = 3: ",md3)
s=1/(1+md3)
print("minkowski similarity : ",s)